### ISSUE TITLE
remove tuples from weaver

### ISSUE THREAD

**Issue by jasonwoods-7** [jasonwoods-7/Vandelay#98]
tuples in the weaver are throwing the following exception:

```
Severity	Code	Description	Line	Project	File	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\src\VandelayTest\packages\Vandelay.Fody.0.8.0\build\..\weaver\Vandelay.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 213
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 110
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
Type:
System.IO.FileNotFoundException
StackTrace:
   at Vandelay.Fody.ModuleWeaver.InjectRetriever(TypeReference importType, IReadOnlyCollection`1 searchPatterns)
   at Vandelay.Fody.ModuleWeaver.ProcessImportMany(MethodDefinition method, Instruction instruction, IGenericInstance methodReference)
   at Vandelay.Fody.ModuleWeaver.ProcessInstruction(MethodDefinition method, Instruction instruction)
   at Vandelay.Fody.ModuleWeaver.Process(MethodDefinition method)
   at Vandelay.Fody.ModuleWeaver.HandleImports()
   at Vandelay.Fody.ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 184
Source:
Vandelay.Fody
TargetSite:
Mono.Cecil.MethodDefinition InjectRetriever(Mono.Cecil.TypeReference, System.Collections.Generic.IReadOnlyCollection`1[System.String])
Could not load file or assembly 'System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
Type:
System.IO.FileNotFoundException
```

**Comment by nipampatel** [comment]
ModuleWeaver.Retriever.cs Has method which uses Tuple. Fixing that should fix issue. It fixed for me locally.

(FieldDefinition defintion, ArrayType collectionType)
      InjectImportsField(TypeReference importType)

**Comment by nipampatel** [comment]
@jasonwoods-7 

class ImportMetadata
  {
    public FieldDefinition Defintion { get;set;} = null!;
    public ArrayType CollectionType { get;set;} = null!;
  }
